### ISSUE TITLE
Separate module from model definition, instantiate modules in SSLModel

### ISSUE THREAD

**Issue by ryanccarelli** [ryanccarelli/ssljax#97]
Currently we instantiate modules in Branch by iterating over each branch's config self.config.model.branches.items(). This change instantiates modules instead in SSLModel, then passes these built modules to branches.

Advantages:
1.  Parameter sharing: We can easily tie parameters by calling the same module twice in different branches.
2. Modularity: Branches are now just wrappers around composition.

Here is a scheme with parameter sharing:
```
modules:
  body1:
    name: ResNet
    params: {}
  head1:
    name: MLP
    params: {}

model:
  name: SSLModel
  branches:
    0:
      body: body1
      head: head1
    1:
      body: body1
```
